name: Check and update changelog

on:
  pull_request:
    types: [opened, edited]

jobs:
  go-changelog:
    runs-on: ubuntu-latest
    container:
      image: docker://giantswarm/go-changelog
      volumes:
        - ${{ github.workspace }}:/github/workspace
    steps:
      - uses: actions/checkout@v2

      - name: mkdir
        run: mkdir -p /github/workspace/.changelog

      - name: Check PR body
        run: /go-changelog/changelog-pr-body-check -pull-request ${{ github.event.number }} -output-path /github/workspace/.changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload changelog directory
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: /github/workspace/.changelog

  commit-changes:
    runs-on: ubuntu-latest
    needs: [go-changelog]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download changelog directory
        uses: actions/download-artifact@v2
        with:
          name: changelog

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply go-changelog changes
