name: Project Labels
on:
  issues:
    types: [labeled]   # This workflow is triggered when issues are labeled.
jobs:
  job:
    name: Create Project Card
    runs-on: ubuntu-latest
    steps:
    - name: Create Project Card for Issue in appropriate Project Column
      run: |
        curl https://api.github.com/projects/columns/6900249/cards \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'Accept: application/vnd.github.inertia-preview+json' \
        --data "{\"content_id\": $(cat $GITHUB_EVENT_PATH | jq .issue.id), \"content_type\": \"Issue\"}"
