name: Check and update changelog

on:
  pull_request:
    types: [opened, edited]

jobs:
  debug_info:
    name: Debug info
    runs-on: ubuntu-20.04
    steps:
      - name: Print github context JSON
        run: |
          cat <<EOF
          ${{ toJson(github) }}
          EOF

  gather_facts:
    name: Gather facts
    runs-on: ubuntu-20.04
    outputs:
      skip: ${{ steps.gather_facts.outputs.skip }}
    steps:
      - name: Gather facts
        id: gather_facts
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          head="${{ github.event.pull_request.head.ref }}"
          echo $head
          if [[ "$head" =~ "^.+#release#.+" ]]; then
            echo "::set-output name=skip::true"
          else
            echo "::set-output name=skip::false"
          fi

  go-changelog:
    runs-on: ubuntu-latest
    needs:
      - gather_facts
    if: ${{ needs.gather_facts.outputs.skip != 'true' }}
    container:
      image: docker://giantswarm/go-changelog:0.0.0-1cc37556d1acbd1e079a146338b84c2ab9b7d9a4
      volumes:
        - ${{ github.workspace }}:/github/workspace
    steps:
      - uses: actions/checkout@v2

      - name: Check PR body
        run: /go-changelog/changelog-pr-body-check -pull-request ${{ github.event.number }} -output-path /github/workspace/.changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload changelog directory
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: .changelog

  commit-changes:
    runs-on: ubuntu-latest
    needs: [go-changelog]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download changelog directory
        uses: actions/download-artifact@v2
        with:
          path: .changelog
          name: changelog

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply go-changelog changes
